project:
  type: website

website:
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  title: "OSCSA"
  favicon: favicon.png
  page-navigation: true
  page-footer:
    left:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Promoting Open Science inline with Vision 2030"
        href: https://osc-ksa.com/
    right:
      - icon: twitter
        href: https://twitter.com/OpenSciSaudi
        aria-label: OSCSA Twitter
      - icon: github
        href: https://github.com/Open-Science-Community-Saudi-Arabia
        aria-label: OSCSA GitHub
  search: true
  navbar:
    background: light
    collapse-below: lg
    logo: logo3.png
    title: false
    right:
      - text: "عربي"
        href: ar/index.html
      - icon: github
        href: https://github.com/Open-Science-Community-Saudi-Arabia
      - icon: twitter
        href: https://twitter.com/OpenSciSaudi
    left:
      - text: "Main Website"
        href: https://osc-ksa.com/
      - text: "About"
        href: about.qmd
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css

execute:
  freeze: auto
